### ISSUE TITLE
Support for client traffic routing?

### ISSUE THREAD

**Issue by funkenstrahlen** [Stouts/Stouts.openvpn#10]
Does this role support client traffic routing via openvpn server?

In other words: I connect to the openvpn server and all my traffic (to the internet) gets routed through the server.

**Comment by j-carpentier** [comment]
Hello !
I think this role doesn't support traffic routing via OpenVPN server
I'm looking for exactly the same thing and it's seems some key features are unhandled
iptables rules or forwarding enabled (/proc/sys/net/ipv4/ip_forward)

Take a look at this article :
http://allanmcrae.com/2013/09/routing-traffic-with-openvpn/

**Comment by fitz123** [comment]
Guys, it support routing traffic. You just need to choose this connection as Default Gateway. For example on Linux by default all traffic goes thru VPN connection. On windows I guess you need to mark  some checkbox

**Comment by mightydok** [comment]
@funkenstrahlen add this to your config for client defgw support:
```
openvpn_server_options:
 - push "dhcp-option DNS IP_OF_DNS_SERVER"
 - push "redirect-gateway def1 bypass-dhcp"
```

**Comment by conorsch** [comment]
I'm using a separate firewall role to handle iptables rules. The [sysctl options mentioned above](https://github.com/Stouts/Stouts.openvpn/issues/10#issuecomment-131616515) are indeed handled, since #25. Therefore this seems OK to close. 

Docs PRs to make practical usage more clear are welcome!
