### ISSUE TITLE
Client setup?

### ISSUE THREAD

**Issue by mikysal78** [Stouts/Stouts.openvpn#112]
- hosts: test
  become: "{{ become | default('yes') }}"
  roles:
    - Stouts.openvpn
  vars:
    openvpn_dev: vpnbas
    openvpn_max_clients: 256
    openvpn_key_country: IT
    openvpn_key_province: MT
    openvpn_key_city: Matera
    openvpn_key_org: Ninux Basilicata
    openvpn_key_email: basilicata@ml.ninux.org
    openvpn_key_size: 2048
    openvpn_use_pam: no
    openvpn_cipher: none
    openvpn_keepalive: "5 60"
    openvpn_topology: subnet
    openvpn_server: 10.27.253.0 255.255.255.0
    openvpn_clients: []
    openvpn_simple_auth: yes
    openvpn_simple_auth_password: passtestpass
    openvpn_bridge:
        address: 10.27.253.1
        netmask: 255.255.255.0
        network: 10.27.253.0
        broadcast: 10.27.253.255
        dhcp_start: 10.27.253.2
        dhcp_end: 10.27.253.254
    openvpn_server_options:
        - "dev-type tap"
        - "client-to-client"
        - "username-as-common-name"
        - "client-cert-not-required"
        - "tls-server"
        - "fast-io"

for esport config client?

**Comment by nkakouros** [comment]
@mikysal78 It is not clear to me what your issue is about, could you provide more details?

**Comment by nkakouros** [comment]
Actually, this role does not configure the vpn client, only the server. If that was not the original issue, feel free to reopen this.
