### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by iachievedit** [Stouts/Stouts.openvpn#124]
I'm working through issues using this role on Ubuntu 18.04 (which includes OpenSSL 1.1.0), will do my best to provide an updates directly to the project.

**Comment by nkakouros** [comment]
That sounds great! You might also want to take a look at #109 , #84 and #110 .

**Comment by danitfk** [comment]
@iachievedit 
Hey Dude, What is the status of your working about this Issue?
If you didn't start yet, Let me know.
Thank you :smile:

**Comment by iachievedit** [comment]
@danitfk I am just about to start now :-) Once again I have been blocked by this.

**Comment by jjmpsp** [comment]
Would love to hear how things go with this

**Comment by daleosm** [comment]
Yes please

**Comment by iachievedit** [comment]
I've issued a PR for this https://github.com/Stouts/Stouts.openvpn/pull/128.  Whether this is elegant is debatable, but it is the same fix as on Stretch.

**Comment by daleosm** [comment]
Cheers for going out your way to provide a fix.

**Comment by mojojoseph** [comment]
Thanks @daleosm unfortunately this hasn't been pulled in yet!

**Comment by iachievedit** [comment]
Thanks @daleosm unfortunately this hasn't been pulled in yet!

@nkakouros do you think this PR is ready to merge?  Thanks so much.

**Comment by iachievedit** [comment]
I guess not! :-)

**Comment by mcdir** [comment]
@iachievedit  Please take a look at https://github.com/Stouts/Stouts.openvpn/pull/132

**Comment by nkakouros** [comment]
This role does not handle certificates on its own anymore. Personally, I use [this role](https://github.com/nkakouros-original/ansible-role-easyrsa) for my certificate needs. It uses version 3 of EasyRSA which is much simpler to work with.

Thanks to everyone for their patience and work.
