### ISSUE TITLE
CRL defaults to 30 days

### ISSUE THREAD

**Issue by apiening** [Stouts/Stouts.openvpn#134]
The default value for CRL expiration is set to 30 days only in `easyrsa/openssl-1.0.0.cnf` in the provided `easy_rsa.tar.gz` from files:
```
default_crl_days= 30                  # how long before next CRL
```
This leaves no clients to be able to connect 30 days after one client was revoked.

I think updating the value to 3065 for example would be fine.
Providing a setting to override this value would be also an option.

**Comment by nkakouros** [comment]
This role does not handle certificates on its own anymore. Personally, I use [this role](https://github.com/nkakouros-original/ansible-role-easyrsa) for my certificate needs. It allows you to set the CRL expiration.
