### ISSUE TITLE
Generates Certs In the Future

### ISSUE THREAD

**Issue by Ttech** [Stouts/Stouts.openvpn#136]
When certs are generated they are for 1 day in the future. Generated on Ubuntu 18.04 dest, with Centos 8 ansible host.  Also crl file isn't generating but still included in directives.

**Comment by nkakouros** [comment]
This role does not handle certificates on its own anymore. Personally, I use [this role](https://github.com/nkakouros-original/ansible-role-easyrsa) for my certificate needs.
