### ISSUE TITLE
make ldap URI configurable

### ISSUE THREAD

**Issue by exeral** [Stouts/Stouts.openvpn#138]
ldap**s** (LDAP over SSL) support is missing since ldap uri scheme is hardcoded:
`URL   ldap://{{ openvpn_ldap_server }}`

making uri scheme configurable would allow to use ldaps.

I can do a PR,
I would have done this by putting the whole string in {{ openvpn_ldap_server }} but this will break backward compatibility.
so,
create another parameter {{ openvpn_ldap_scheme }} ?

**Comment by exeral** [comment]
on hold, since I'm not even sur openvpn ldap support ldaps ...!

**Comment by nkakouros** [comment]
It would be great to have a PR. They way I would approach this would be to not introduce yet another variable, but check if `openvpn_ldap_server` contains the protocol. If it does, output it as is. If it doesn't prepend the `ldap://` string, together with a comment explaining why and backwards compatibility.
