### ISSUE TITLE
No package matching 'module-init-tools' is available (debian10)

### ISSUE THREAD

**Issue by exeral** [Stouts/Stouts.openvpn#143]
Hi,

I just pulled new changes. including 4bcda3cffa9c8ae8a051c4023367c4bcaa4891bc
this adds tasks/system/firewall.yml
which tries to install **module-init-tools** on Debian

This package is only available on jessie (oldoldstable) : https://packages.debian.org/search?keywords=module-init-tools&searchon=names&suite=all&section=all

This break compatibility with many other Debian versions.
in my case it's Buster(10):

> TASK [openvpn : Install firewall dependencies (Debian)] *************************************************************************************************************************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "msg": "No package matching 'module-init-tools' is available"}

**Comment by nkakouros** [comment]
I think I have fixed this. Let me know how it goes.

**Comment by exeral** [comment]
I don't want to use the firewall, so
`openvpn_open_firewall: false
openvpn_route_traffic: false
`
does the job for me.

I have not tested with firewall enabled on Debian 10
