### ISSUE TITLE
Conditional check fails

### ISSUE THREAD

**Issue by alanmcg** [Stouts/Stouts.openvpn#147]
Getting the following error since yesterdays commits ( https://github.com/Stouts/Stouts.openvpn/commit/bc31ccafadd9b7813bf39684cacbb4a1bf9baac9 )

`fatal: [openvpn]: FAILED! => {"msg": "The conditional check 'iptables_rules.stdout.find(\"incoming_openvpn\") == -1' failed. The error was: error while evaluating conditional (iptables_rules.stdout.find(\"incoming_openvpn\") == -1): 'dict object' has no attribute 'stdout'\n\nThe error appears to be in '/home/user/.ansible/roles/openvpn/tasks/system/firewall-open.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Allow connections to the OpenVPN server\n  ^ here\n"} `

Had a look  but can't see the direct cause.

**Comment by nkakouros** [comment]
How have you configured the role? Could you provide the values for the role variables you use?

**Comment by alanmcg** [comment]
Sure:

```
openvpn_host: '14.38.60.137'
openvpn_server: 10.11.1.0 255.255.255.0
openvpn_keydir: '{{ easyrsa_pki_dir }}'
openvpn_status: openvpn-status.log
openvpn_clients:
- client
openvpn_comp_lzo: false
openvpn_tls_auth: true
openvpn_route_traffic: true
openvpn_unified_client_profiles: true # client.ovpn files is embedded with cert
openvpn_cipher: AES-256-CBC
openvpn_route_ranges:
- 172.34.0.0 255.255.0.0
- 10.130.0.0 255.255.0.0
openvpn_dns_servers:
  - 172.34.0.2
openvpn_server_options:
  - push "route 32.71.155.0 255.255.255.255" 
  - duplicate-cn
```

**Comment by nkakouros** [comment]
I can't reproduce it. The issue seems to be that the task `Read existing iptables rules` in `tasks/system/firewall-deps.yml` gets skipped or sth. Can you provide the output of ansible with `-vvv` for this task until the one that fails?

Also, if you manually run `sudo iptables -L` on the server, what happens?

**Comment by alanmcg** [comment]
I can no longer reproduce it either, we made some significant changes to our ansible layout which might have caused this along the way. It's fixed now in any case, thanks for your help anyway!
