### ISSUE TITLE
I have error in log with execve

### ISSUE THREAD

**Issue by mikysal78** [Stouts/Stouts.openvpn#168]
https://github.com/Stouts/Stouts.openvpn/blob/6f87890db67ef62ed691a0ab95fe6822e9767397/templates/server.conf.j2#L175

**Comment by nkakouros** [comment]
Could you enrich your reports with a bit more context? For instance, what is the error you get?

**Comment by mikysal78** [comment]
> Could you enrich your reports with a bit more context? For instance, what is the error you get?

root@openwisp:openvpn # tail -f /var/log/openvpn.log 
Tue Oct 13 12:42:51 2020 oppido-c2600/192.168.1.100:51648 MULTI: Learn: ae:15:3c:c8:f3:b2 -> oppido-c2600/192.168.1.100:51648
Tue Oct 13 12:55:10 2020 event_wait : Interrupted system call (code=4)
Tue Oct 13 12:55:10 2020 Closing TUN/TAP interface
Tue Oct 13 12:55:10 2020 SIGTERM[hard,] received, process exiting
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/server.conf:118: script-security (2.4.7)
Use --help for more information.

If remove "execve" from server.conf it's ok.
I test now remove from template and is ok...
I using debian buster!

**Comment by mikysal78** [comment]
remove execve from template on [Line 175](https://github.com/Stouts/Stouts.openvpn/blob/6f87890db67ef62ed691a0ab95fe6822e9767397/templates/server.conf.j2#L175)
