### ISSUE TITLE
Certificate password

### ISSUE THREAD

**Issue by fitz123** [Stouts/Stouts.openvpn#18]
Hi there! What do you think about using password for certificates?
Also on whom are you aim usage? I did some development to make passwords, it works fine for me. But also I aim configuration to WIndows users, so I included fingerprint into client config to let clients use WIndows Cert Store as it is way more secure than keep cert as a file in the system

If you're interested I can make precise pull request with some of these features

**Comment by nemesisdesign** [comment]
I believe this is the same thing for which I sent a pull request: #27.
Try it out and let us know if it works for you.
If it does then we can close this issue.

**Comment by conorsch** [comment]
#27 was merged, so closing.
