### ISSUE TITLE
fix crl.pem permissions after client revoke

### ISSUE THREAD

**Issue by fitz123** [Stouts/Stouts.openvpn#20]
```
  stat: path={{openvpn_keydir}}/crl.pem
   register: crl_pem_file

+- name: Check crl.pem ACL
+  file: path={{openvpn_keydir}}/crl.pem
+        owner={{ openvpn_user }} mode=400
+
 - name: Generate Clients configurations
   template: src=client.conf.j2 dest={{openvpn_keydir}}/{{item.item.item.name}}.ovpn
   with_items: cert_fp.results
```

After client revoke crt.pem owner and group is root. Openvpn cannot restart

**Comment by nkakouros** [comment]
This role does not handle certificates on its own anymore. Personally, I use [this role](https://github.com/nkakouros-original/ansible-role-easyrsa) for my certificate needs. I have no issues working with a CRL this way. See the README for more details.
