### ISSUE TITLE
Client configuration managment

### ISSUE THREAD

**Issue by deimosfr** [Stouts/Stouts.openvpn#3]
Hi,

Really nice job for this role (like your other ones ;-) ). It would be good to be able to manage clients with previously generated certs. What do you think about it ?

Thanks

**Comment by klen** [comment]
Sorry I have no time. May be you will be able to provide a pull request?

**Comment by conorsch** [comment]
Hello @deimosfr. This role is very focused on managing the openvpn server, so shoehorning in client management would only complicate things. Note that the role conveniently zips up client configs via a handler, so you can fetch them back to the Ansible controller in a subsequent task. I recommend adding a play to to your vpn playbook that then configures the clients based on those secrets.
