### ISSUE TITLE
Ansible 2 requires variable quotation

### ISSUE THREAD

**Issue by froztbyte** [Stouts/Stouts.openvpn#31]
It seems that as of release 2.0 there are different requirements on variable quoting. See https://docs.ansible.com/ansible/porting_guide_2.0.html#deprecated for more details.

**Comment by nemesisdesign** [comment]
Was this forgot to be closed or is it still open?

**Comment by conorsch** [comment]
@nemesisdesign Thanks for the nudge, let me confirm that #32 handled all of the deprecation warnings, then we can close this.

**Comment by nemesisdesign** [comment]
Ok maybe better to attract @klen's attention so he can close this.

**Comment by froztbyte** [comment]
@conorsch if you could do that, it would be appreciated. I saw #30 only after I'd actually done my bits, but also found an item covered in #32 that wasn't in #30, so I'm not sure where this stands.

**Comment by conorsch** [comment]
I no longer see any deprecation warnings running under Ansible v2.1.0, so closing this issue. Thanks, @froztbyte!
