### ISSUE TITLE
Update galaxy

### ISSUE THREAD

**Issue by mamoit** [Stouts/Stouts.openvpn#36]
Latest version in galaxy is `2.0.5` and the current version is `2.2.0`.

**Comment by elricsfate** [comment]
@mamoit 

Galaxy seems to indicate 2.2.0 but after installing I seem to get an old version that doesn't even support Ubuntu Xenial? 

Can anyone else confirm this bug?

**Comment by nfedyashev** [comment]
@elricsfate

I installed Stouts.openvpn from ansible galaxy and that's what it looks like:

    ✗ ansible --version
    ansible 2.2.0.0

    TASK [Stouts.openvpn : include_vars] *******************************************
    fatal: [sovereign.host]: FAILED! => {"failed": true, "msg": "Unable to find 'Ubuntu.xenial.yml' in expected paths."}

**Comment by nfedyashev** [comment]
@elricsfate instead of galaxy version I used that repo instead and it works now. Galaxy version is outdated indeed

/cc @klen

**Comment by 030** [comment]
```
the specified version (2.3.2) of Stouts.openvpn was not found in the list of available versions ([{u'name': u'2.2.0', u'created'
```

**Comment by nemesisdesign** [comment]
@conorsch could you update ansible-galaxy?

**Comment by conorsch** [comment]
@nemesisdesign Yes, thanks for the nudge. A lot as been merged recently, so I'm going to bump the version to 2.4 prior to updating galaxy.

**Comment by conorsch** [comment]
New version 2.4.0 is live on Galaxy. Will try to stay on top of this, but feel free to open an issue in the future if it lags again!

**Comment by nemesisdesign** [comment]
thank you very much @conorsch
