### ISSUE TITLE
easy-rsa auditability

### ISSUE THREAD

**Issue by robbintt** [Stouts/Stouts.openvpn#54]
I audited the package in files/easy-rsa.tar.gz file against the source offered by openvpn.  It looks like there are a few lines that are different, so I still do not know the entire audit trail for this file.

https://github.com/OpenVPN/easy-rsa/tree/release/2.x

This would take much less effort to audit if there was some versioning method available such as the git commit or version number or sha hash for whatever version this easy-rsa.tar.gz file is.

Even better would be a sub repository.

**Comment by conorsch** [comment]
Note #43, which allows installation of system easy-rsa packages from the distro repo. That may be a better solution for your use case.

**Comment by nkakouros** [comment]
EasyRSA is no longer bundled with the role and the role expects the user to generate certs/keys using a different method (see the README for an example using an easyrsa role).
