### ISSUE TITLE
.tar.gz not spawning in /etc/openvpn

### ISSUE THREAD

**Issue by JeanFrancoisMaes** [Stouts/Stouts.openvpn#72]
I only have a zip file, I guess thats an error in the docs? 
Also, I only see one key and one cert generated called client 
Should the vpn users be added to the openvpn_clients?

**Comment by nkakouros** [comment]
You are right about the tar file, I fixed the README. And yes, `openvpn_clients` needs to reflect `openvpn_use_pam_users`.
