### ISSUE TITLE
masquerade firewall rule 

### ISSUE THREAD

**Issue by JeanFrancoisMaes** [Stouts/Stouts.openvpn#73]
apparently this role does not add the masquerade firewall rule. This caused my VPN connection to lose internet access when connected

**Comment by xahare** [comment]
can you elaborate? did you want tun0 natted? for most use cases you can nat the default interface on the vpn server.

**Comment by AndresPineros** [comment]
This would be a nice addition. It isn't very hard to add to the role. In fact, I had to extend the role myself to accomplish the internet outbound connection.
