### ISSUE TITLE
management option ?

### ISSUE THREAD

**Issue by livilu** [Stouts/Stouts.openvpn#80]
Thinking in adding management option ?
It's just a line in the config: management 127.0.0.1 5555
Found this only thing missing from my perspective

**Comment by fundo-dev** [comment]
You could use variable `openvpn_server_options` like this:
```
openvpn_server_options:
  - management 127.0.0.1 5555
```

**Comment by nkakouros** [comment]
Closing as @fundo-dev's suggestion covers this and there is #115 pending.
