### ISSUE TITLE
The task includes an option with an undefined variable

### ISSUE THREAD

**Issue by nleo** [Stouts/Stouts.openvpn#97]
After change `openvpn_unified_client_profiles` from `no` to `yes` got error    

    TASK [Stouts.openvpn : Set client cert and CA info as fact.] *******************
    fatal: [xxx]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'content'\n\nThe error appears to have been in '/home/user/.ansible/roles/Stouts.openvpn/tasks/read-client-files.yml': line 30, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set client cert and CA info as fact.\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'content'"}

Local machine

    Linux netbook 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:14:44 UTC 2017 i686 i686 i686 GNU/Linux
    ansible 2.4.1.0
      config file = /etc/ansible/ansible.cfg
      configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python2.7/dist-packages/ansible
      executable location = /usr/bin/ansible
      python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

Server

    Ubuntu 16.04.3 LTS
    Python 3.5.2

**Comment by gnasr** [comment]
same issue here
`osx sierra`
```
ansible 2.3.2.0
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

**Comment by DanielLimanowski** [comment]
Having the exact same issue on Ubuntu 16.04.3 LTS with Python 3.5. Was working yesterday oddly enough, now I cannot get it to run on a different instance.

**Comment by kwach** [comment]
+1

**Comment by gnasr** [comment]
This PR solves this issue https://github.com/Stouts/Stouts.openvpn/pull/88 i forked this repo and merged it

**Comment by nleo** [comment]
So, I need some simple OpenVPN installation without passwords, only ovpn files with integrated certificates. And I use this https://github.com/Nyr/openvpn-install to install and initial config of OpenVPN server and make some ansible tasks myself to tweak it and add users.

For me issue resolved)
